export const SHOW_LOAN_DETAIL = 'SHOW_LOAN_DETAIL';
export const HIDE_LOAN_DETAIL = 'HIDE_LOAN_DETAIL';
export const ADD_ERROR_AMOUNT_EXCEDED = 'ADD_ERROR_AMOUNT_EXCEDED';
export const REMOVE_ERROR_AMOUNT_EXCEDED = 'REMOVE_ERROR_AMOUNT_EXCEDED';
